### ISSUE TITLE
github doesent detect capitalizeation as a change

### ISSUE THREAD

**Issue by tobyplowy** [SummerFields/DataBase#4]
i renamed apple to Apple but github doesent detect the change how can i fix this?

**Comment by lipki** [comment]
at home it works.
I'll look.

**Comment by lipki** [comment]
@tobyplowy  https://www.garron.me/en/bits/git-ignorecase-rename-lowercase-uppercase.html

**Comment by tobyplowy** [comment]
@lipki ok thanks I will have a look in to it :)

**Comment by lipki** [comment]
https://github.com/orgs/SummerFields/teams/global-manager/discussions/1?from_reply=7#discussion-1-comment-7

**Comment by lipki** [comment]
Why did I close?
